/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rentalmanagement;

/**
 *
 * @author EDALIA. M
 */
public class assignHouse extends javax.swing.JFrame {

    /**
     * Creates new form viewVacancies
     */
    public assignHouse() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        Home = new javax.swing.JButton();
        logo = new javax.swing.JLabel();
        userHome = new javax.swing.JLabel();
        fName = new javax.swing.JTextField();
        lName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        userID = new javax.swing.JTextField();
        first = new javax.swing.JLabel();
        last = new javax.swing.JLabel();
        contract = new javax.swing.JLabel();
        houseTypeText = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        houseType = new javax.swing.JLabel();
        number = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Allocate House");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        panel1.setName(""); // NOI18N
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Home.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Home.setText("< Back");
        Home.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });
        panel1.add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 110, 50));

        logo.setFont(new java.awt.Font("Viner Hand ITC", 1, 18)); // NOI18N
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rentalmanagement/Home.png"))); // NOI18N
        logo.setText("R.M.S");
        panel1.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 0, -1, -1));

        userHome.setBackground(new java.awt.Color(0, 102, 153));
        userHome.setOpaque(true);
        panel1.add(userHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 100));

        fName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        panel1.add(fName, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, 180, -1));

        lName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        panel1.add(lName, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, 180, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("User ID:");
        panel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, -1, 30));

        userID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        panel1.add(userID, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 290, 180, -1));

        first.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        first.setText("First Name:");
        panel1.add(first, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, -1, -1));

        last.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        last.setText("Last Name:");
        panel1.add(last, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, -1, -1));

        contract.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        contract.setText("Contract ID:");
        panel1.add(contract, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 370, 90, -1));
        panel1.add(houseTypeText, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 450, 170, -1));

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        panel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 360, 190, -1));

        houseType.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        houseType.setText("House Type:");
        panel1.add(houseType, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 450, -1, -1));

        number.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        number.setText("House Number:");
        panel1.add(number, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 530, -1, -1));

        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        panel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 530, 190, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Confirm");
        panel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 610, -1, 40));

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setOpaque(true);
        panel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 560, 540));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rentalmanagement/Base.png"))); // NOI18N
        panel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        new supervisorHome().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_HomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(assignHouse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(assignHouse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(assignHouse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(assignHouse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new assignHouse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Home;
    private javax.swing.JLabel background;
    private javax.swing.JLabel contract;
    private javax.swing.JTextField fName;
    private javax.swing.JLabel first;
    private javax.swing.JLabel houseType;
    private javax.swing.JTextField houseTypeText;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField lName;
    private javax.swing.JLabel last;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel number;
    private java.awt.Panel panel1;
    private javax.swing.JLabel userHome;
    private javax.swing.JTextField userID;
    // End of variables declaration//GEN-END:variables
}
