/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package rentalmanagement;

/**
 *
 * @author EDALIA. M
 */
import rentalmanagement.*;
public class clientHome extends javax.swing.JFrame {

    /**
     * Creates new form clientHome
     */
    public clientHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        clientPanel = new java.awt.Panel();
        logout = new javax.swing.JButton();
        welcomeLabel = new javax.swing.JLabel();
        greetingLabel = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        logo = new javax.swing.JLabel();
        userHome = new javax.swing.JLabel();
        view_contract = new javax.swing.JLabel();
        update_account1 = new javax.swing.JLabel();
        house_picture = new javax.swing.JLabel();
        view_contract1 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Client:Home");
        setBounds(new java.awt.Rectangle(0, 0, 1300, 700));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        clientPanel.setBackground(new java.awt.Color(51, 51, 51));
        clientPanel.setPreferredSize(new java.awt.Dimension(1300, 700));
        clientPanel.setLayout(null);

        logout.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        logout.setText("Logout");
        logout.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        clientPanel.add(logout);
        logout.setBounds(40, 30, 110, 50);

        welcomeLabel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        welcomeLabel.setForeground(new java.awt.Color(255, 255, 255));
        welcomeLabel.setText("Welcome, ");
        clientPanel.add(welcomeLabel);
        welcomeLabel.setBounds(210, -40, 190, 160);

        greetingLabel.setEditable(false);
        greetingLabel.setBackground(new java.awt.Color(0, 102, 153));
        greetingLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        greetingLabel.setForeground(new java.awt.Color(255, 255, 255));
        greetingLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        greetingLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                greetingLabelActionPerformed(evt);
            }
        });
        clientPanel.add(greetingLabel);
        greetingLabel.setBounds(410, 10, 260, 60);
        clientPanel.add(jSeparator1);
        jSeparator1.setBounds(190, 80, 560, 20);

        logo.setFont(new java.awt.Font("Viner Hand ITC", 1, 18)); // NOI18N
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rentalmanagement/Home.png"))); // NOI18N
        logo.setText("R.M.S");
        clientPanel.add(logo);
        logo.setBounds(1130, 0, 149, 90);

        userHome.setBackground(new java.awt.Color(0, 102, 153));
        userHome.setOpaque(true);
        clientPanel.add(userHome);
        userHome.setBounds(0, 0, 1300, 100);

        view_contract.setBackground(new java.awt.Color(204, 204, 204));
        view_contract.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        view_contract.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rentalmanagement/complaint.png"))); // NOI18N
        view_contract.setText("Complaints & Suggestions");
        view_contract.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        view_contract.setOpaque(true);
        clientPanel.add(view_contract);
        view_contract.setBounds(30, 480, 300, 150);

        update_account1.setBackground(new java.awt.Color(204, 204, 204));
        update_account1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        update_account1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rentalmanagement/details.png"))); // NOI18N
        update_account1.setText("Account Details");
        update_account1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        update_account1.setOpaque(true);
        update_account1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                update_account1MouseClicked(evt);
            }
        });
        clientPanel.add(update_account1);
        update_account1.setBounds(30, 110, 240, 130);

        house_picture.setBackground(new java.awt.Color(204, 204, 204));
        house_picture.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 102, 153)));
        house_picture.setOpaque(true);
        clientPanel.add(house_picture);
        house_picture.setBounds(660, 120, 570, 340);

        view_contract1.setBackground(new java.awt.Color(204, 204, 204));
        view_contract1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        view_contract1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rentalmanagement/contract.png"))); // NOI18N
        view_contract1.setText("Contract details and Arreas");
        view_contract1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        view_contract1.setOpaque(true);
        view_contract1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                view_contract1MouseClicked(evt);
            }
        });
        view_contract1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                view_contract1KeyPressed(evt);
            }
        });
        clientPanel.add(view_contract1);
        view_contract1.setBounds(30, 280, 300, 150);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rentalmanagement/Base.png"))); // NOI18N
        clientPanel.add(background);
        background.setBounds(0, 100, 1300, 600);

        getContentPane().add(clientPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
      new userLogin().setVisible(true);
      this.dispose();
    }//GEN-LAST:event_logoutActionPerformed

    private void greetingLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_greetingLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_greetingLabelActionPerformed

    private void update_account1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_update_account1MouseClicked
        new clientAccount().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_update_account1MouseClicked

    private void view_contract1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_view_contract1KeyPressed
    
    }//GEN-LAST:event_view_contract1KeyPressed

    private void view_contract1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_view_contract1MouseClicked
        new Contract().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_view_contract1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(clientHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(clientHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(clientHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(clientHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new clientHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private java.awt.Panel clientPanel;
    private javax.swing.JTextField greetingLabel;
    private javax.swing.JLabel house_picture;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel logo;
    private javax.swing.JButton logout;
    private javax.swing.JLabel update_account1;
    private javax.swing.JLabel userHome;
    private javax.swing.JLabel view_contract;
    private javax.swing.JLabel view_contract1;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
