/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rentalmanagement;

/**
 *
 * @author EDALIA. M
 */
public class clientAccount extends javax.swing.JFrame {

    /**
     * Creates new form updateAc
     */
    public clientAccount() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
   
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        updatePanel = new java.awt.Panel();
        Home = new javax.swing.JButton();
        logo = new javax.swing.JLabel();
        userHome = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        phone_number = new javax.swing.JLabel();
        password_change = new javax.swing.JLabel();
        confirm_password = new javax.swing.JLabel();
        confirm = new javax.swing.JButton();
        username = new javax.swing.JTextField();
        changePasswordField = new javax.swing.JPasswordField();
        confirmPasswordField1 = new javax.swing.JPasswordField();
        name = new javax.swing.JLabel();
        houseNum = new javax.swing.JLabel();
        numberHouse = new javax.swing.JTextField();
        houseType1 = new javax.swing.JLabel();
        houseType = new javax.swing.JTextField();
        Phone_number1 = new javax.swing.JTextField();
        password_label1 = new javax.swing.JLabel();
        supervisor_name = new javax.swing.JTextField();
        houseNum1 = new javax.swing.JLabel();
        changeNum = new javax.swing.JButton();
        save = new javax.swing.JButton();
        userDetail = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Update Account");
        setBounds(new java.awt.Rectangle(0, 0, 1300, 700));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        updatePanel.setPreferredSize(new java.awt.Dimension(1300, 700));
        updatePanel.setLayout(null);

        Home.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Home.setText("< Back");
        Home.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });
        updatePanel.add(Home);
        Home.setBounds(40, 30, 110, 50);

        logo.setFont(new java.awt.Font("Viner Hand ITC", 1, 18)); // NOI18N
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rentalmanagement/Home.png"))); // NOI18N
        logo.setText("R.M.S");
        updatePanel.add(logo);
        logo.setBounds(1130, 0, 149, 90);

        userHome.setBackground(new java.awt.Color(0, 102, 153));
        userHome.setOpaque(true);
        updatePanel.add(userHome);
        userHome.setBounds(0, 0, 1300, 100);

        jLabel1.setText("jLabel1");
        updatePanel.add(jLabel1);
        jLabel1.setBounds(340, 20, 250, 50);

        phone_number.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        phone_number.setText("Phone number:");
        updatePanel.add(phone_number);
        phone_number.setBounds(60, 330, 130, 50);

        password_change.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        password_change.setText("Change Password:");
        updatePanel.add(password_change);
        password_change.setBounds(640, 270, 150, 30);

        confirm_password.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        confirm_password.setText("Confirm Password:");
        updatePanel.add(confirm_password);
        confirm_password.setBounds(640, 310, 160, 40);

        confirm.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        confirm.setText("Confirm Change");
        updatePanel.add(confirm);
        confirm.setBounds(710, 400, 150, 40);

        username.setEditable(false);
        username.setBackground(new java.awt.Color(204, 204, 204));
        username.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        username.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        updatePanel.add(username);
        username.setBounds(170, 289, 310, 20);
        updatePanel.add(changePasswordField);
        changePasswordField.setBounds(770, 270, 160, 28);
        updatePanel.add(confirmPasswordField1);
        confirmPasswordField1.setBounds(770, 320, 160, 28);

        name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        name.setText("Name:");
        updatePanel.add(name);
        name.setBounds(120, 290, 70, 17);

        houseNum.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        houseNum.setText("Supervisor/Landlord:");
        updatePanel.add(houseNum);
        houseNum.setBounds(50, 600, 160, 17);

        numberHouse.setEditable(false);
        numberHouse.setBackground(new java.awt.Color(204, 204, 204));
        numberHouse.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        numberHouse.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        updatePanel.add(numberHouse);
        numberHouse.setBounds(190, 490, 70, 19);

        houseType1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        houseType1.setText("House Type:");
        updatePanel.add(houseType1);
        houseType1.setBounds(90, 450, 110, 17);

        houseType.setEditable(false);
        houseType.setBackground(new java.awt.Color(204, 204, 204));
        houseType.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        houseType.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        updatePanel.add(houseType);
        houseType.setBounds(190, 450, 200, 19);

        Phone_number1.setEditable(false);
        Phone_number1.setBackground(new java.awt.Color(204, 204, 204));
        Phone_number1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Phone_number1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Phone_number1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Phone_number1ActionPerformed(evt);
            }
        });
        updatePanel.add(Phone_number1);
        Phone_number1.setBounds(180, 340, 170, 30);

        password_label1.setBackground(new java.awt.Color(204, 204, 204));
        password_label1.setOpaque(true);
        updatePanel.add(password_label1);
        password_label1.setBounds(590, 210, 380, 260);

        supervisor_name.setBackground(new java.awt.Color(204, 204, 204));
        supervisor_name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        supervisor_name.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        updatePanel.add(supervisor_name);
        supervisor_name.setBounds(210, 600, 230, 19);

        houseNum1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        houseNum1.setText("House Number:");
        updatePanel.add(houseNum1);
        houseNum1.setBounds(70, 490, 110, 17);

        changeNum.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        changeNum.setText("Change");
        changeNum.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        changeNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeNumActionPerformed(evt);
            }
        });
        updatePanel.add(changeNum);
        changeNum.setBounds(360, 340, 90, 30);

        save.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        save.setText("Save");
        save.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        updatePanel.add(save);
        save.setBounds(280, 390, 80, 30);

        userDetail.setBackground(new java.awt.Color(204, 204, 204));
        userDetail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        userDetail.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        userDetail.setOpaque(true);
        updatePanel.add(userDetail);
        userDetail.setBounds(0, 210, 490, 440);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rentalmanagement/Base.png"))); // NOI18N
        updatePanel.add(background);
        background.setBounds(0, 100, 1300, 600);

        getContentPane().add(updatePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        new clientHome().setVisible(true);
        save.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_HomeActionPerformed

    private void changeNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeNumActionPerformed
        Phone_number1.setEditable(true);
        save.setVisible(true);
    }//GEN-LAST:event_changeNumActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        save.setVisible(false);
        Phone_number1.setEditable(false);
    }//GEN-LAST:event_saveActionPerformed

    private void Phone_number1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Phone_number1ActionPerformed
       
    }//GEN-LAST:event_Phone_number1ActionPerformed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(clientAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(clientAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(clientAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(clientAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold
        //</editor-fold
        //</editor-fold
        //</editor-fold

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new clientAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Home;
    private javax.swing.JTextField Phone_number1;
    private javax.swing.JLabel background;
    private javax.swing.JButton changeNum;
    private javax.swing.JPasswordField changePasswordField;
    private javax.swing.JButton confirm;
    private javax.swing.JPasswordField confirmPasswordField1;
    private javax.swing.JLabel confirm_password;
    private javax.swing.JLabel houseNum;
    private javax.swing.JLabel houseNum1;
    private javax.swing.JTextField houseType;
    private javax.swing.JLabel houseType1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel name;
    private javax.swing.JTextField numberHouse;
    private javax.swing.JLabel password_change;
    private javax.swing.JLabel password_label1;
    private javax.swing.JLabel phone_number;
    private javax.swing.JButton save;
    private javax.swing.JTextField supervisor_name;
    private java.awt.Panel updatePanel;
    private javax.swing.JLabel userDetail;
    private javax.swing.JLabel userHome;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
