/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rentalmanagement;

/**
 *
 * @author EDALIA. M
 */
public class Contract extends javax.swing.JFrame {

    /**
     * Creates new form Contract
     */
    public Contract() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel2 = new java.awt.Panel();
        Home = new javax.swing.JButton();
        logo = new javax.swing.JLabel();
        userHome = new javax.swing.JLabel();
        arreas = new javax.swing.JTextField();
        rentpaid1 = new javax.swing.JLabel();
        rentMax = new javax.swing.JLabel();
        rentpaid2 = new javax.swing.JLabel();
        rentPaid = new javax.swing.JTextField();
        contract = new javax.swing.JLabel();
        contract_ID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        houseType = new javax.swing.JTextField();
        maxRent1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        houseNum1 = new javax.swing.JLabel();
        numberHouse1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Contract and arreas");
        setMinimumSize(new java.awt.Dimension(1300, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel2.setPreferredSize(new java.awt.Dimension(1300, 700));
        panel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Home.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Home.setText("< Back");
        Home.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });
        panel2.add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 110, 50));

        logo.setFont(new java.awt.Font("Viner Hand ITC", 1, 18)); // NOI18N
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rentalmanagement/Home.png"))); // NOI18N
        logo.setText("R.M.S");
        panel2.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 0, -1, -1));

        userHome.setBackground(new java.awt.Color(0, 102, 153));
        userHome.setOpaque(true);
        panel2.add(userHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 100));

        arreas.setEditable(false);
        arreas.setBackground(new java.awt.Color(204, 204, 204));
        arreas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        arreas.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        panel2.add(arreas, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 360, 150, 30));

        rentpaid1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rentpaid1.setText("Rent Paid: Ksh");
        panel2.add(rentpaid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 290, 120, -1));

        rentMax.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rentMax.setText("Max Rent: Ksh");
        panel2.add(rentMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, 110, -1));

        rentpaid2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rentpaid2.setText("Rent Arreas: Ksh");
        panel2.add(rentpaid2, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 370, 140, -1));

        rentPaid.setEditable(false);
        rentPaid.setBackground(new java.awt.Color(204, 204, 204));
        rentPaid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rentPaid.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        panel2.add(rentPaid, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 279, 150, 30));

        contract.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        contract.setText("Contract ID:");
        panel2.add(contract, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));

        contract_ID.setEditable(false);
        contract_ID.setBackground(new java.awt.Color(204, 204, 204));
        contract_ID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        contract_ID.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        panel2.add(contract_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 218, 190, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("House Type:");
        panel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 100, -1));

        houseType.setEditable(false);
        houseType.setBackground(new java.awt.Color(204, 204, 204));
        houseType.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        houseType.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        houseType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                houseTypeActionPerformed(evt);
            }
        });
        panel2.add(houseType, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 190, 30));

        maxRent1.setEditable(false);
        maxRent1.setBackground(new java.awt.Color(204, 204, 204));
        maxRent1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        maxRent1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        panel2.add(maxRent1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, 150, 30));

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setOpaque(true);
        panel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 220, 390, 220));

        houseNum1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        houseNum1.setText("House Number:");
        panel2.add(houseNum1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 110, -1));

        numberHouse1.setEditable(false);
        numberHouse1.setBackground(new java.awt.Color(204, 204, 204));
        numberHouse1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        numberHouse1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        panel2.add(numberHouse1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 70, 30));

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setOpaque(true);
        panel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 390, 270));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rentalmanagement/Base.png"))); // NOI18N
        panel2.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1300, 600));

        getContentPane().add(panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 0, 1300, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        new clientHome().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_HomeActionPerformed

    private void houseTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_houseTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_houseTypeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Contract.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Contract.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Contract.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Contract.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Contract().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Home;
    private javax.swing.JTextField arreas;
    private javax.swing.JLabel background;
    private javax.swing.JLabel contract;
    private javax.swing.JTextField contract_ID;
    private javax.swing.JLabel houseNum1;
    private javax.swing.JTextField houseType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel logo;
    private javax.swing.JTextField maxRent1;
    private javax.swing.JTextField numberHouse1;
    private java.awt.Panel panel2;
    private javax.swing.JLabel rentMax;
    private javax.swing.JTextField rentPaid;
    private javax.swing.JLabel rentpaid1;
    private javax.swing.JLabel rentpaid2;
    private javax.swing.JLabel userHome;
    // End of variables declaration//GEN-END:variables
}
