/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rentalmanagement;

/**
 *
 * @author EDALIA. M
 */
public class signUp extends javax.swing.JFrame {

    /**
     * Creates new form signUp
     */
    public signUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        firstName1 = new javax.swing.JTextField();
        lastName1 = new javax.swing.JTextField();
        phoneNumber1 = new javax.swing.JTextField();
        email1 = new javax.swing.JTextField();
        userID = new javax.swing.JLabel();
        fName1 = new javax.swing.JLabel();
        lName1 = new javax.swing.JLabel();
        phone_number = new javax.swing.JLabel();
        emailAddress = new javax.swing.JLabel();
        create_password = new javax.swing.JLabel();
        Complete = new javax.swing.JButton();
        confirm_password1 = new javax.swing.JLabel();
        confirmPassword = new javax.swing.JPasswordField();
        createPassword1 = new javax.swing.JPasswordField();
        confirmPassword1 = new javax.swing.JPasswordField();
        Sign_up = new javax.swing.JLabel();
        logout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();
        userHome = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sign Up");
        setName("Sign up"); // NOI18N

        panel1.setPreferredSize(new java.awt.Dimension(700, 600));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        firstName1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        firstName1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel1.add(firstName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 210, -1));

        lastName1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lastName1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel1.add(lastName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 210, -1));

        phoneNumber1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        phoneNumber1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel1.add(phoneNumber1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 210, -1));

        email1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        email1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel1.add(email1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 210, -1));

        userID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        userID.setText("Your User ID is:");
        panel1.add(userID, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 490, 140, -1));

        fName1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fName1.setText("First Name:");
        panel1.add(fName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 100, -1));

        lName1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lName1.setText("Last Name:");
        panel1.add(lName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 100, -1));

        phone_number.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        phone_number.setText("Phone number:");
        panel1.add(phone_number, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 120, -1));

        emailAddress.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        emailAddress.setText("email:");
        panel1.add(emailAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 60, -1));

        create_password.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        create_password.setText("Password:");
        panel1.add(create_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 100, -1));

        Complete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Complete.setText("Confirm");
        Complete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompleteActionPerformed(evt);
            }
        });
        panel1.add(Complete, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 460, 120, 60));

        confirm_password1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        confirm_password1.setText("Confirm Password:");
        panel1.add(confirm_password1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, 140, -1));

        confirmPassword.setEditable(false);
        confirmPassword.setBackground(new java.awt.Color(204, 204, 204));
        confirmPassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        confirmPassword.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        confirmPassword.setOpaque(true);
        panel1.add(confirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 480, 200, 28));

        createPassword1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        createPassword1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel1.add(createPassword1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, 200, -1));

        confirmPassword1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        confirmPassword1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel1.add(confirmPassword1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 410, 200, 28));

        Sign_up.setBackground(new java.awt.Color(255, 255, 255));
        Sign_up.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Sign_up.setForeground(new java.awt.Color(255, 255, 255));
        Sign_up.setText("Sign Up");
        panel1.add(Sign_up, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 150, 50));

        logout.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        logout.setText("Login");
        logout.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        panel1.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, 40));

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setOpaque(true);
        panel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 400, 450));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rentalmanagement/Base.png"))); // NOI18N
        panel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 700, 540));

        userHome.setBackground(new java.awt.Color(0, 102, 153));
        userHome.setOpaque(true);
        panel1.add(userHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CompleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompleteActionPerformed
      
    }//GEN-LAST:event_CompleteActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        new userLogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Complete;
    private javax.swing.JLabel Sign_up;
    private javax.swing.JLabel background;
    private javax.swing.JPasswordField confirmPassword;
    private javax.swing.JPasswordField confirmPassword1;
    private javax.swing.JLabel confirm_password1;
    private javax.swing.JPasswordField createPassword1;
    private javax.swing.JLabel create_password;
    private javax.swing.JTextField email1;
    private javax.swing.JLabel emailAddress;
    private javax.swing.JLabel fName1;
    private javax.swing.JTextField firstName1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lName1;
    private javax.swing.JTextField lastName1;
    private javax.swing.JButton logout;
    private java.awt.Panel panel1;
    private javax.swing.JTextField phoneNumber1;
    private javax.swing.JLabel phone_number;
    private javax.swing.JLabel userHome;
    private javax.swing.JLabel userID;
    // End of variables declaration//GEN-END:variables
}
