/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rentalmanagement;

/**
 *
 * @author EDALIA. M
 */
public class supervisorAccount extends javax.swing.JFrame {

    /**
     * Creates new form updateSupervisor
     */
    public supervisorAccount() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        phone_number = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        name = new javax.swing.JLabel();
        Phone_number1 = new javax.swing.JTextField();
        password_change1 = new javax.swing.JLabel();
        confirm_password1 = new javax.swing.JLabel();
        confirm1 = new javax.swing.JButton();
        changeNum = new javax.swing.JButton();
        Home = new javax.swing.JButton();
        save = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        password_label1 = new javax.swing.JLabel();
        userDetail = new javax.swing.JLabel();
        background = new javax.swing.JLabel();
        logo1 = new javax.swing.JLabel();
        userHome = new javax.swing.JLabel();
        password_label3 = new javax.swing.JLabel();
        confirm3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel1.setLayout(null);

        phone_number.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        phone_number.setText("Phone number:");
        panel1.add(phone_number);
        phone_number.setBounds(60, 330, 130, 50);

        username.setEditable(false);
        username.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        username.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        panel1.add(username);
        username.setBounds(170, 290, 270, 30);

        name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        name.setText("Name:");
        panel1.add(name);
        name.setBounds(120, 290, 70, 17);

        Phone_number1.setEditable(false);
        Phone_number1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Phone_number1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Phone_number1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Phone_number1ActionPerformed(evt);
            }
        });
        panel1.add(Phone_number1);
        Phone_number1.setBounds(180, 340, 170, 30);

        password_change1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        password_change1.setText("Change Password:");
        panel1.add(password_change1);
        password_change1.setBounds(670, 260, 150, 30);

        confirm_password1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        confirm_password1.setText("Confirm Password:");
        panel1.add(confirm_password1);
        confirm_password1.setBounds(670, 300, 160, 40);

        confirm1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        confirm1.setText("Confirm Change");
        panel1.add(confirm1);
        confirm1.setBounds(740, 390, 150, 40);

        changeNum.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        changeNum.setText("Change");
        changeNum.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        changeNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeNumActionPerformed(evt);
            }
        });
        panel1.add(changeNum);
        changeNum.setBounds(370, 350, 90, 30);

        Home.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Home.setText("< Back");
        Home.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });
        panel1.add(Home);
        Home.setBounds(40, 30, 110, 50);

        save.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        save.setText("Save");
        save.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        panel1.add(save);
        save.setBounds(180, 400, 80, 30);
        panel1.add(jPasswordField1);
        jPasswordField1.setBounds(820, 260, 170, 30);
        panel1.add(jPasswordField2);
        jPasswordField2.setBounds(820, 310, 160, 28);

        password_label1.setBackground(new java.awt.Color(204, 204, 204));
        password_label1.setOpaque(true);
        panel1.add(password_label1);
        password_label1.setBounds(620, 200, 380, 260);

        userDetail.setBackground(new java.awt.Color(204, 204, 204));
        userDetail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        userDetail.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        userDetail.setOpaque(true);
        panel1.add(userDetail);
        userDetail.setBounds(0, 210, 490, 240);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rentalmanagement/Base.png"))); // NOI18N
        panel1.add(background);
        background.setBounds(0, 100, 1300, 600);

        logo1.setFont(new java.awt.Font("Viner Hand ITC", 1, 18)); // NOI18N
        logo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rentalmanagement/Home.png"))); // NOI18N
        logo1.setText("R.M.S");
        panel1.add(logo1);
        logo1.setBounds(1130, 0, 149, 90);

        userHome.setBackground(new java.awt.Color(0, 102, 153));
        userHome.setOpaque(true);
        panel1.add(userHome);
        userHome.setBounds(0, 0, 1300, 100);

        password_label3.setBackground(new java.awt.Color(204, 204, 204));
        password_label3.setOpaque(true);
        panel1.add(password_label3);
        password_label3.setBounds(770, 110, 380, 260);

        confirm3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        confirm3.setText("Confirm Change");
        panel1.add(confirm3);
        confirm3.setBounds(890, 300, 150, 40);

        getContentPane().add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Phone_number1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Phone_number1ActionPerformed

    }//GEN-LAST:event_Phone_number1ActionPerformed

    private void changeNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeNumActionPerformed
        Phone_number1.setEditable(true);
        save.setVisible(true);
    }//GEN-LAST:event_changeNumActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        save.setVisible(false);
        Phone_number1.setEditable(false);
    }//GEN-LAST:event_saveActionPerformed

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        new supervisorHome().setVisible(true);
        save.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_HomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(supervisorAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(supervisorAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(supervisorAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(supervisorAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new supervisorAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Home;
    private javax.swing.JTextField Phone_number1;
    private javax.swing.JLabel background;
    private javax.swing.JButton changeNum;
    private javax.swing.JButton confirm1;
    private javax.swing.JButton confirm3;
    private javax.swing.JLabel confirm_password1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JLabel logo1;
    private javax.swing.JLabel name;
    private java.awt.Panel panel1;
    private javax.swing.JLabel password_change1;
    private javax.swing.JLabel password_label1;
    private javax.swing.JLabel password_label3;
    private javax.swing.JLabel phone_number;
    private javax.swing.JButton save;
    private javax.swing.JLabel userDetail;
    private javax.swing.JLabel userHome;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
