/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rentalmanagement;

/**
 *
 * @author EDALIA. M
 */
public class tenantStatus extends javax.swing.JFrame {

    /**
     * Creates new form tenantStatus
     */
    public tenantStatus() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        Home = new javax.swing.JButton();
        logo = new javax.swing.JLabel();
        userHome = new javax.swing.JLabel();
        Bungalow = new javax.swing.JLabel();
        maisonette_pane = new javax.swing.JScrollPane();
        maisonette_table = new javax.swing.JTable();
        Flat_label = new javax.swing.JLabel();
        Maisonette = new javax.swing.JLabel();
        bungalow_pane = new javax.swing.JScrollPane();
        bungalow_table = new javax.swing.JTable();
        Flat = new javax.swing.JScrollPane();
        flatTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tenant Status");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel1.setLayout(null);

        Home.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Home.setText("< Back");
        Home.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });
        panel1.add(Home);
        Home.setBounds(40, 30, 110, 50);

        logo.setFont(new java.awt.Font("Viner Hand ITC", 1, 18)); // NOI18N
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rentalmanagement/Home.png"))); // NOI18N
        logo.setText("R.M.S");
        panel1.add(logo);
        logo.setBounds(1130, 0, 149, 90);

        userHome.setBackground(new java.awt.Color(0, 102, 153));
        userHome.setOpaque(true);
        panel1.add(userHome);
        userHome.setBounds(0, 0, 1300, 100);

        Bungalow.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Bungalow.setText("Bungalow");
        panel1.add(Bungalow);
        Bungalow.setBounds(1050, 170, 130, 22);

        maisonette_table.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        maisonette_table.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        maisonette_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "First Name", "Last Name", "Contract ID", "Arreas"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        maisonette_table.getTableHeader().setResizingAllowed(false);
        maisonette_pane.setViewportView(maisonette_table);
        if (maisonette_table.getColumnModel().getColumnCount() > 0) {
            maisonette_table.getColumnModel().getColumn(0).setResizable(false);
            maisonette_table.getColumnModel().getColumn(1).setResizable(false);
            maisonette_table.getColumnModel().getColumn(2).setResizable(false);
            maisonette_table.getColumnModel().getColumn(3).setResizable(false);
        }

        panel1.add(maisonette_pane);
        maisonette_pane.setBounds(470, 200, 380, 370);

        Flat_label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Flat_label.setText("Flats");
        panel1.add(Flat_label);
        Flat_label.setBounds(190, 170, 70, 22);

        Maisonette.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Maisonette.setText("Maisonette");
        panel1.add(Maisonette);
        Maisonette.setBounds(600, 180, 130, 22);

        bungalow_table.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bungalow_table.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bungalow_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "First Name", "Last Name", "Contract ID", "Arreas"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        bungalow_table.getTableHeader().setResizingAllowed(false);
        bungalow_pane.setViewportView(bungalow_table);
        if (bungalow_table.getColumnModel().getColumnCount() > 0) {
            bungalow_table.getColumnModel().getColumn(0).setResizable(false);
            bungalow_table.getColumnModel().getColumn(1).setResizable(false);
            bungalow_table.getColumnModel().getColumn(2).setResizable(false);
            bungalow_table.getColumnModel().getColumn(3).setResizable(false);
        }

        panel1.add(bungalow_pane);
        bungalow_pane.setBounds(910, 200, 380, 370);

        flatTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        flatTable.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        flatTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "First Name", "Last Name", "Contract ID", "Arreas"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        flatTable.getTableHeader().setResizingAllowed(false);
        Flat.setViewportView(flatTable);
        if (flatTable.getColumnModel().getColumnCount() > 0) {
            flatTable.getColumnModel().getColumn(0).setResizable(false);
            flatTable.getColumnModel().getColumn(1).setResizable(false);
            flatTable.getColumnModel().getColumn(2).setResizable(false);
            flatTable.getColumnModel().getColumn(3).setResizable(false);
        }

        panel1.add(Flat);
        Flat.setBounds(50, 200, 380, 370);

        jLabel1.setOpaque(true);
        panel1.add(jLabel1);
        jLabel1.setBounds(10, 150, 1280, 450);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rentalmanagement/Base.png"))); // NOI18N
        panel1.add(background);
        background.setBounds(0, 100, 1300, 600);

        getContentPane().add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        new supervisorHome().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_HomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tenantStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tenantStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tenantStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tenantStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tenantStatus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bungalow;
    private javax.swing.JScrollPane Flat;
    private javax.swing.JLabel Flat_label;
    private javax.swing.JButton Home;
    private javax.swing.JLabel Maisonette;
    private javax.swing.JLabel background;
    private javax.swing.JScrollPane bungalow_pane;
    private javax.swing.JTable bungalow_table;
    private javax.swing.JTable flatTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel logo;
    private javax.swing.JScrollPane maisonette_pane;
    private javax.swing.JTable maisonette_table;
    private java.awt.Panel panel1;
    private javax.swing.JLabel userHome;
    // End of variables declaration//GEN-END:variables
}
